typography_spectrum: 0.27815
color:
  brandColors:
    - '#4c4968'
    - '#bcc348'
    - '#f1f1f2'
    - '#000000'
    - '#a7a6b4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.76279
analytics:
  google: null
  facebook: null
  twitter: null
name: Relevance Path
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    url: paulives.ca
    type: external
favicon: null
purpose: []
