name: Relevance Path
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2781527799088508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4a69'
    - '#bdc345'
    - '#dee4a3'
    - '#a5a3b3'
    - '#7f7c93'
  brandStrength: 0.25559289823286235
  lightness: 0.2689819009974599
  saturation: 0.5394642355386168
  rhythmicContrast: 0.5
purpose: []
