name: Relevance Path
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4a69'
    - '#bdc345'
    - '#dee4a3'
    - '#a5a3b3'
    - '#7f7c93'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
