name: Relevance Path
favicon: null
layout_spectrum: 0.76279
typography_spectrum: 0.27815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c4968'
    - '#bcc348'
    - '#f1f1f2'
    - '#000000'
    - '#a7a6b4'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
